### PR TITLE
Import order

### LINKED ISSUE #30: Standardize import order
also undo what Bram did and move functional outside of imports

### LINKED ISSUE #32: give restart the reload alias as well

### PR DESCRIPTION
**Pull request by Koramund**
closes #30 
closes #32 

Look github does not give me an easy way to mark this PR as dependent, gitlab ftw

depends on #34

### CODE REVIEW

**Comment by juliavdkris** [comment]
Damn I coulda sworn GitHub had support for MR dependencies, but apparently not.

Though I would recommend merging this into embeds, and then merging #34 into master, instead of both merging into master separately? That also sorta indicates a dependency relation, and makes sure we don't need to check the same code twice

https://github.com/juliavdkris/dotobot/compare/embeds...import-order vs https://github.com/juliavdkris/dotobot/compare/master...import-order

**Comment by Koramund** [comment]
This just builds upon embeds so approving that first and then opening this up you will see only the things related to this branch. Otherwise you're mixing things, I don't mind but you were saying something about not mixing commits since it makes big reviews

**Comment by juliavdkris** [comment]
Ahh yea that's true, I actually didn't even think of the fact that merging this into embeds would add these changes to that comparison as well

Also, I thought draft pull requests were only for teams/enterprise plans? Apparently they're free for public repos, that's neat

**Comment by juliavdkris** [comment]
Also we coooouuuld probably use a GitHub action thing for MR dependencies, I'd bet someone already made that a thing

**Comment by juliavdkris** [comment]
Something like https://www.dpulls.com/ or https://github.com/z0al/dependent-issues

**Comment by juliavdkris** [comment]
I don't see a difference between these force pushed commits I'm so confused lmao

**Review by juliavdkris — APPROVED** [review]
LGTM tho

**Pull request merged**
